Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  
Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/dwh/adapters/**/*.rb'

Metrics/PerceivedComplexity:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
