name: Test and Document 

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.4'
    env:
      BUNDLE_WITHOUT: 'development'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run the default task
        run: bundle exec rake test:unit

  docs:
    runs-on: ubuntu-latest
    needs: test # This job runs only after 'test' completes successfully
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    env:
      BUNDLE_WITHOUT: 'development'

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.4'
        bundler-cache: true
    
    - name: Generate documentation
      run: bundle exec rake doc
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
